version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - clinic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/clinic
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  clinic:
    image: 'postgres:13.1-alpine'
    container_name: clinic
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
